---
title: "Cobb-Douglas"
author: "Hans Elliott"
format: html
editor: visual
---
`r Sys.Date()`

```{r}
#| echo: false
#| message: false
#| warning: false
if (!require("pacman")) install.packages("pacman")
pacman::p_load(plotly, ggplot2)

# https://web.holycross.edu/RePEc/eej/Archive/Volume31/V31N3P427_445.pdf
```


```{r}
# Original Dataset from Cobb-Doublas 1928
# https://web.holycross.edu/RePEc/eej/Archive/Volume31/V31N3P427_445.pdf
table = "Year Output Labor Capital
1899 100 100 100
1900 101 105 107
1901 112 110 114
1902 122 118 122
1903 124 123 131
1904 122 116 138
1905 143 125 149
1906 152 133 163
1907 151 138 176
1908 126 121 185
1909 155 140 198
1910 159 144 208
1911 153 145 216
1912 177 152 226
1913 184 154 236
1914 169 149 244
1915 189 154 266
1916 225 182 298
1917 227 196 335
1918 223 200 366
1919 218 193 387
1920 231 193 407
1921 179 147 417
1922 240 161 431
"
table = strsplit(table, split="\n")[[1]]
data_1928 = NULL
for (line in table) {
  row = strsplit(line, split=" ")[[1]]
  if (row[1] == "Year") next
  year = as.integer(row[1])
  output = as.numeric(row[2])
  labor = as.numeric(row[3])
  capital = as.numeric(row[4])
  data_1928 = rbind(data_1928, data.frame(year,output,labor,capital))
}
```



```{r}
cobb_douglas = function(L, K, A=1.01, alpha=0.75) {
  # P(L, K) = A * L^(alpha) * K^(1-alpha)
  # L : labor
  # K : capital
  # A : total factor productivity
  # alpha : output elasticity of labor
  # 1-alpha: output elasticity of capital
  return( A * L**alpha * K**(1-alpha) )
}
```


```{r}
# Implied Total Factor Productivity
factor_productivity = function(P, L, K, alpha=0.75) {
  # A = P / [L^(alpha) * K^(1-alpha)]
  return(
    P / (L**alpha *  K**(1-alpha))
  )  
}

data_1928["productivity"] = mapply(factor_productivity, 
                                   data_1928$output, 
                                   data_1928$labor,
                                   data_1928$capital)
data_1928


ggplot(data_1928, aes(x=year)) +
  geom_line(aes(y=labor, color="Labor")) +
  geom_line(aes(y=capital, color="Capital")) +
  geom_line(aes(y=output, color="Output")) +
  theme_minimal() +
  labs(y=NULL, color=NULL)

ggplot(data_1928) +
  geom_line(aes(x=year, y = productivity)) +
  theme_minimal()

```



```{r}
# Plotting the Cobb-Douglas Function
n_dim = 300
P = outer(0:n_dim, 0:n_dim, FUN = cobb_douglas, A = 1, alpha = 0.75)

# Looks like y = Labor, x = Capital
plotly::plot_ly(z=~P) |> 
  plotly::add_surface() |> 
    layout(title = 'Cobb-Douglas Production Function', 
           plot_bgcolor = "#e5ecf6")
```


```{r}
# Isoquants
contour(P)
```






